FROM golang:1.18.1 AS development
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go install github.com/cespare/reflex@latest
EXPOSE 8080
CMD reflex -g '*.go' go run edgemgmt/server/edgemgmt_server.go --start-service