// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: edgemgmt/edgemgmt.proto

package go_edgemgmt_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewDevice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchantID string `protobuf:"bytes,1,opt,name=merchantID,proto3" json:"merchantID,omitempty"`
	DeviceID   int32  `protobuf:"varint,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
}

func (x *NewDevice) Reset() {
	*x = NewDevice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edgemgmt_edgemgmt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDevice) ProtoMessage() {}

func (x *NewDevice) ProtoReflect() protoreflect.Message {
	mi := &file_edgemgmt_edgemgmt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDevice.ProtoReflect.Descriptor instead.
func (*NewDevice) Descriptor() ([]byte, []int) {
	return file_edgemgmt_edgemgmt_proto_rawDescGZIP(), []int{0}
}

func (x *NewDevice) GetMerchantID() string {
	if x != nil {
		return x.MerchantID
	}
	return ""
}

func (x *NewDevice) GetDeviceID() int32 {
	if x != nil {
		return x.DeviceID
	}
	return 0
}

type ActivationStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchantID   string `protobuf:"bytes,1,opt,name=merchantID,proto3" json:"merchantID,omitempty"`
	DeviceID     int32  `protobuf:"varint,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	DeviceStatus string `protobuf:"bytes,3,opt,name=deviceStatus,proto3" json:"deviceStatus,omitempty"`
}

func (x *ActivationStatus) Reset() {
	*x = ActivationStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edgemgmt_edgemgmt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationStatus) ProtoMessage() {}

func (x *ActivationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_edgemgmt_edgemgmt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationStatus.ProtoReflect.Descriptor instead.
func (*ActivationStatus) Descriptor() ([]byte, []int) {
	return file_edgemgmt_edgemgmt_proto_rawDescGZIP(), []int{1}
}

func (x *ActivationStatus) GetMerchantID() string {
	if x != nil {
		return x.MerchantID
	}
	return ""
}

func (x *ActivationStatus) GetDeviceID() int32 {
	if x != nil {
		return x.DeviceID
	}
	return 0
}

func (x *ActivationStatus) GetDeviceStatus() string {
	if x != nil {
		return x.DeviceStatus
	}
	return ""
}

type Payment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentRefNo   string `protobuf:"bytes,1,opt,name=paymentRefNo,proto3" json:"paymentRefNo,omitempty"`
	PaymentDetails string `protobuf:"bytes,2,opt,name=paymentDetails,proto3" json:"paymentDetails,omitempty"`
}

func (x *Payment) Reset() {
	*x = Payment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edgemgmt_edgemgmt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_edgemgmt_edgemgmt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_edgemgmt_edgemgmt_proto_rawDescGZIP(), []int{2}
}

func (x *Payment) GetPaymentRefNo() string {
	if x != nil {
		return x.PaymentRefNo
	}
	return ""
}

func (x *Payment) GetPaymentDetails() string {
	if x != nil {
		return x.PaymentDetails
	}
	return ""
}

type PaymentStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentRefNo  string `protobuf:"bytes,1,opt,name=paymentRefNo,proto3" json:"paymentRefNo,omitempty"`
	PaymentStatus string `protobuf:"bytes,2,opt,name=paymentStatus,proto3" json:"paymentStatus,omitempty"`
}

func (x *PaymentStatus) Reset() {
	*x = PaymentStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edgemgmt_edgemgmt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentStatus) ProtoMessage() {}

func (x *PaymentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_edgemgmt_edgemgmt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentStatus.ProtoReflect.Descriptor instead.
func (*PaymentStatus) Descriptor() ([]byte, []int) {
	return file_edgemgmt_edgemgmt_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentStatus) GetPaymentRefNo() string {
	if x != nil {
		return x.PaymentRefNo
	}
	return ""
}

func (x *PaymentStatus) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

var File_edgemgmt_edgemgmt_proto protoreflect.FileDescriptor

var file_edgemgmt_edgemgmt_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x64, 0x67, 0x65, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x65, 0x64, 0x67, 0x65, 0x6d,
	0x67, 0x6d, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x64, 0x67, 0x65, 0x6d,
	0x67, 0x6d, 0x74, 0x22, 0x47, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x22, 0x72, 0x0a, 0x10,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x55, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x4e, 0x6f, 0x12,
	0x26, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x59, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x4e, 0x6f, 0x12, 0x24, 0x0a, 0x0d,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x32, 0x58, 0x0a, 0x0e, 0x45, 0x64, 0x67, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x46, 0x0a, 0x11, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x4e, 0x65, 0x77, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x65, 0x64, 0x67, 0x65,
	0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x4e, 0x65, 0x77, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1a,
	0x2e, 0x65, 0x64, 0x67, 0x65, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x32, 0x4d, 0x0a, 0x0b,
	0x45, 0x64, 0x67, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x0e, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x11, 0x2e,
	0x65, 0x64, 0x67, 0x65, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x1a, 0x17, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x65, 0x64,
	0x67, 0x65, 0x6d, 0x67, 0x6d, 0x74, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x67, 0x6f, 0x5f, 0x65,
	0x64, 0x67, 0x65, 0x6d, 0x67, 0x6d, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_edgemgmt_edgemgmt_proto_rawDescOnce sync.Once
	file_edgemgmt_edgemgmt_proto_rawDescData = file_edgemgmt_edgemgmt_proto_rawDesc
)

func file_edgemgmt_edgemgmt_proto_rawDescGZIP() []byte {
	file_edgemgmt_edgemgmt_proto_rawDescOnce.Do(func() {
		file_edgemgmt_edgemgmt_proto_rawDescData = protoimpl.X.CompressGZIP(file_edgemgmt_edgemgmt_proto_rawDescData)
	})
	return file_edgemgmt_edgemgmt_proto_rawDescData
}

var file_edgemgmt_edgemgmt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_edgemgmt_edgemgmt_proto_goTypes = []interface{}{
	(*NewDevice)(nil),        // 0: edgemgmt.NewDevice
	(*ActivationStatus)(nil), // 1: edgemgmt.ActivationStatus
	(*Payment)(nil),          // 2: edgemgmt.Payment
	(*PaymentStatus)(nil),    // 3: edgemgmt.PaymentStatus
}
var file_edgemgmt_edgemgmt_proto_depIdxs = []int32{
	0, // 0: edgemgmt.EdgeManagement.ActivateNewDevice:input_type -> edgemgmt.NewDevice
	2, // 1: edgemgmt.EdgePayment.ProcessPayment:input_type -> edgemgmt.Payment
	1, // 2: edgemgmt.EdgeManagement.ActivateNewDevice:output_type -> edgemgmt.ActivationStatus
	3, // 3: edgemgmt.EdgePayment.ProcessPayment:output_type -> edgemgmt.PaymentStatus
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_edgemgmt_edgemgmt_proto_init() }
func file_edgemgmt_edgemgmt_proto_init() {
	if File_edgemgmt_edgemgmt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_edgemgmt_edgemgmt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDevice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edgemgmt_edgemgmt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivationStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edgemgmt_edgemgmt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edgemgmt_edgemgmt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_edgemgmt_edgemgmt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_edgemgmt_edgemgmt_proto_goTypes,
		DependencyIndexes: file_edgemgmt_edgemgmt_proto_depIdxs,
		MessageInfos:      file_edgemgmt_edgemgmt_proto_msgTypes,
	}.Build()
	File_edgemgmt_edgemgmt_proto = out.File
	file_edgemgmt_edgemgmt_proto_rawDesc = nil
	file_edgemgmt_edgemgmt_proto_goTypes = nil
	file_edgemgmt_edgemgmt_proto_depIdxs = nil
}
